# Generated by Django 6.0 on 2026-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
