# Generated by Django 6.0 on 2026-01-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_categoria_nombre_en_categoria_nombre_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ficha_tecnica',
            field=models.TextField(blank=True, help_text='Ej: Formato: 4K, Cámara: Alexa Mini, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VideoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(help_text='Pega el link de YouTube o Vimeo')),
                ('titulo_video', models.CharField(blank=True, help_text='Opcional: Ej. Trailer, Detrás de escena', max_length=200, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sitioweb.proyecto')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
