# Generated by Django 6.0 on 2026-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0003_proyecto_ficha_tecnica_alter_proyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ficha_tecnica_en',
            field=models.TextField(blank=True, help_text='Ej: Formato: 4K, Cámara: Alexa Mini, etc.', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ficha_tecnica_es',
            field=models.TextField(blank=True, help_text='Ej: Formato: 4K, Cámara: Alexa Mini, etc.', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ficha_tecnica_fr',
            field=models.TextField(blank=True, help_text='Ej: Formato: 4K, Cámara: Alexa Mini, etc.', null=True),
        ),
    ]
