# Generated by Django 6.0 on 2026-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0004_proyecto_ficha_tecnica_en_proyecto_ficha_tecnica_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='url_video',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ficha_tecnica_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ficha_tecnica_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ficha_tecnica_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
