# Generated by Django 6.0 on 2026-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0005_remove_proyecto_url_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
