# Generated by Django 6.0 on 2026-01-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0006_proyecto_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tagline_es',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tagline_fr',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
