# Generated by Django 6.0 on 2026-01-09 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0007_proyecto_tagline_en_proyecto_tagline_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Joaco', max_length=100)),
                ('foto_principal', models.ImageField(upload_to='perfil/')),
                ('bio_corta', models.TextField(help_text='Texto introductorio')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto / Párrafo'), ('IMAGEN', 'Captura de Pantalla / Foto'), ('VIDEO', 'Video (Link de Vimeo/YouTube)')], max_length=10)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='about_galeria/')),
                ('video_url', models.URLField(blank=True, help_text='Embed link', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='sitioweb.perfil')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
