# Generated by Django 6.0 on 2026-01-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0008_perfil_contenidoabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoabout',
            name='texto_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidoabout',
            name='texto_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidoabout',
            name='texto_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_corta_en',
            field=models.TextField(help_text='Texto introductorio', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_corta_es',
            field=models.TextField(help_text='Texto introductorio', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_corta_fr',
            field=models.TextField(help_text='Texto introductorio', null=True),
        ),
    ]
