# Generated by Django 6.0 on 2026-01-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0009_contenidoabout_texto_en_contenidoabout_texto_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bio_corta',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio_corta_en',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio_corta_es',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio_corta_fr',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto_principal',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_detallada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_detallada_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_detallada_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_detallada_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_introduccion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_introduccion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio_introduccion_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to='perfil/foto/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_en',
            field=models.CharField(default='Joaco', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_es',
            field=models.CharField(default='Joaco', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_fr',
            field=models.CharField(default='Joaco', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='Joaco', max_length=200),
        ),
        migrations.CreateModel(
            name='CapturaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='perfil/capturas/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='sitioweb.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(help_text='Link de YouTube o Vimeo')),
                ('titulo_video', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_video_es', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_video_en', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_video_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sitioweb.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='ContenidoAbout',
        ),
    ]
