# Generated by Django 6.0 on 2026-01-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0010_remove_perfil_bio_corta_remove_perfil_bio_corta_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/foto/'),
        ),
    ]
