# Generated by Django 6.0 on 2026-01-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0011_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='CV en PDF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp (ej: 56912345678)'),
        ),
    ]
