# Generated by Django 6.0 on 2026-01-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0012_perfil_cv_pdf_perfil_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_estreno']},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sub_categoria',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('videoclip', 'Videoclip'), ('experimental', 'Experimental')], default='ficcion', max_length=20, verbose_name='Sub-categoría'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
