# Generated by Django 6.0 on 2026-01-22 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0013_alter_proyecto_options_proyecto_sub_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-estreno_anio']},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_estreno',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estreno_anio',
            field=models.PositiveIntegerField(blank=True, help_text='Ingrese el año en formato YYYY', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2031)], verbose_name='Año de estreno'),
        ),
    ]
