# Generated by Django 6.0 on 2026-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0017_proyecto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría'),
        ),
    ]
